### ISSUE TITLE
issue when running python src/main.py

### ISSUE THREAD

**Issue by danilotpnta** [GoncaloBFM/mma2024#8]
Hi, 

I have followed the getting started from the main page. When i run `python src/main.py` , I get the following issue:

```
Calculating clip embeddings
100%|███████████████████████████████████████████████████████████████████████████████| 1000/1000 [01:10<00:00, 14.18it/s]
OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead.
[2]    38705 segmentation fault  python src/main.py
/Users/datoapanta/opt/anaconda3/envs/git-pages/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Environment
- **Operating System**: MacOs, Intel i9, 32GB RAM

How to solve this issue? thanks for the input guys

**Comment by GoncaloBFM** [comment]
Hi, 

did you install the packages on a new environment? It seems you're using anaconda while we're using venv for the project. This should not be a problem but you should be installing the packages on a completely clean environment. 

The problem seems to come from using an outdated package.

Let me know if the problem persists.
